server:
  port: 8301

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: hello-consumer

# 全局ribbon配置
#ribbon:
#  MaxAutoRetries: 3

#指定客户端配置 (就近原则 那个近那个生效)
#hello-provider:
#  ribbon:
#    MaxAutoRetries: 3

#集成hystrix
feign:
  hystrix:
    enabled: true
  #默认是JDK http 替换阿帕奇 http
  httpclient:
    enabled: true
  #压缩
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true


logging:
  config: classpath:logback.xml

