server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes: #路由规则
    film-serivce: #application name 服务名称 service-id
      path: /film-api/** #匹配规则 ? ->单个字符 * ->多个字符 ** ->多个字符并且多及目录



logging:
  config: classpath:logback.xml
